server:
  port: 8083
  servlet:
    context-path: /springai
spring:
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:${OPENAI_KEY}}
      chat: # By default its true, this triggers the autoconfiguration.
        options:
          model: gpt-4
          temperature: 1.0
          max_completion_tokens: 2000
      image:
        api-key: ${OPENAI_API_KEY:${OPENAI_KEY}}
        options:
          model: gpt-image-1
          quality: medium
          height: 1024
          width: 1024


